### ISSUE TITLE
Ver Crossbar.io

### ISSUE THREAD

**Issue by MartinMelo** [MartinMelo/MessageServiceERL#1]
Para sacar ideas

**Comment by mriverov** [comment]
Esta estructura esta buena para tener en cuenta:

# 1) SUBSCRIBE to a topic to receive events
def onhello(msg):
   print("Got event: {}".format(msg))
session.subscribe(onhello, 'com.myapp.hello')

# 2) PUBLISH an event
session.publish('com.myapp.hello', 'Hello, world!')

# 3) REGISTER a procedure for remote calling
def add2(x, y):
   return x + y
session.register(add2, 'com.myapp.add2');

# 4) CALL a remote procedure
result = yield from session.call('com.myapp.add2', 2, 3)
print("Got result: {}".format(result))

**Comment by mriverov** [comment]
Esto esta genial, podemos sacar un par de ejemplo ahi para hacer en la demo:
https://demo.crossbar.io/
Me gusto el de los votos
